### ISSUE TITLE
Create mobile client (Android)

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/RORI#3]
We should be able to use RORI on a phone. Android seems a good choice as wisely used.

**TBD** this is the meta ticket.

+ [ ] Android Client do design
+ [ ] Android Client Run deamon + design
+ [ ] Android client: link mimic
+ [ ] Android client: send first message
