### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/RORI#4]
Like the v3.0.0. **TBD**

+ [ ] Discord client: add issue on RORI
+ [ ] Discord client: do design
+ [ ] Discord client: do channel
+ [ ] Discord client: do bot
